### ISSUE TITLE
Link to Downloads contents not found(404)

### ISSUE THREAD

**Issue by muscle-rabbit** [thomasnield/oreilly_getting_started_with_sql#2]
I appreciate for publishing such a wonderful book.

The top page link is not found. (19/5/1 now)
https://www.dropbox.com/s/e0d67e5wqsxsqmp/getting_started_with_sql_mac.zip?dl=1

Could you retell the link to the contents? 

- I've already signed in Dropbox.

Thanks!

**Comment by productz** [comment]
Could you please update the dropbox link for macOS?

**Comment by thomasnield** [comment]
Hi all, thanks. SQLiteStudio now has installers available. Did you want to try that? I'll update the README if this resolved your issues. 

https://sqlitestudio.pl/index.rvt?act=download

**Comment by productz** [comment]
Yeah. Already gone through the book. It was really fun! Thanks for putting out a great book! 

PS. Found a typo on page 103 (Appendix A5):
**state LIKE 'D_l%' should return 0 (false)**

**Comment by thomasnield** [comment]
@zeedrak, awesome! and thanks, will note for next edition.
