### ISSUE TITLE
Erroneous link

### ISSUE THREAD

**Issue by DrNahtan** [thomasnield/oreilly_getting_started_with_sql#4]
The link that will download a zipped folder containing everything you need, including SQLiteStudio for Mac and the database files doesn't seem to work. 

--> https://www.dropbox.com/s/e0d67e5wqsxsqmp/getting_started_with_sql_mac.zip?dl=1

I've downloaded SQLiteStudio, looking for the databases.

TIA!

**Comment by thomasnield** [comment]
HI @DrNahtan, the databases should be here: 
https://github.com/thomasnield/oreilly_getting_started_with_sql

**Comment by DrNahtan** [comment]
Thomas, 

Thank you. I didn’t realize I needed to select the clone or download button.

Love the book. When I finished, what do you recommend that I move onto next? 

Thank you!
Nathan

**Comment by thomasnield** [comment]
@DrNahtan feel free to email me and I can give recommendations. My email is on my GitHub profile.
